//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fr.IService
{
    using Fr.Model;
    using System;
    using System.Collections.Generic;
    
    public  interface ISysUserService
    {
        bool Add(SysUser user);

        SysUser Get(string userId);

        List<SysUser> GetUserList(int index, int size, out int total);


        SysUser Login(string loginName, string password);
    }
}
