
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fr.Model
{

using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity.ModelConfiguration;
using System;
    using System.Collections.Generic;
    
[Table("Sys_Employee")]
public partial class SysEmployee
{

	/// <summary>
	/// 
	/// </summary>
	
	[StringLength(50)]
	
	public string EmployeeId { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	[StringLength(50)]
	
	public string CompanyId { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	[StringLength(50)]
	
	public string DepartmentId { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	[StringLength(50)]
	
	public string EmployeeName { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	[StringLength(50)]
	
	public string IdCard { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	public System.DateTime? Birthday { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	[StringLength(50)]
	
	public string Phone { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	[StringLength(100)]
	
	public string Email { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	[StringLength(200)]
	
	public string Address { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	public int? Status { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	public System.DateTime? CreateTime { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	[StringLength(50)]
	
	public string CreateUserId { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	[StringLength(200)]
	
	public string CreateUserName { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	public System.DateTime? ModifyTime { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	[StringLength(50)]
	
	public string ModifyUserId { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	[StringLength(200)]
	
	public string ModifyUserNaame { get; set; }

}

internal class SysEmployeeConfig : EntityTypeConfiguration<SysEmployee>
{
    SysEmployeeConfig()
    {
        ToTable("Sys_Employee");
    }
}

}
