
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fr.Model
{

using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity.ModelConfiguration;
using System;
    using System.Collections.Generic;
    
[Table("Sys_Power")]
public partial class SysPower
{

	/// <summary>
	/// 功能Id
	/// </summary>
	
	[StringLength(50)]
	
	public string PowerId { get; set; }

	/// <summary>
	/// 功能编码
	/// </summary>
	
	[StringLength(200)]
	
	public string PowerCode { get; set; }

	/// <summary>
	/// 功能名称
	/// </summary>
	
	[StringLength(200)]
	
	public string PowerName { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	public System.DateTime? CreateTime { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	[StringLength(50)]
	
	public string CreateUserId { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	[StringLength(200)]
	
	public string CreateUserName { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	public System.DateTime? ModifyTime { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	[StringLength(50)]
	
	public string ModifyUserId { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	[StringLength(200)]
	
	public string ModifyUserName { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	public System.DateTime? CreateTime2 { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	[StringLength(50)]
	
	public string CreateUserId2 { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	[StringLength(200)]
	
	public string CreateUserName2 { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	public System.DateTime? ModifyTime2 { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	[StringLength(50)]
	
	public string ModifyUserId2 { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	[StringLength(200)]
	
	public string ModifyUserName2 { get; set; }

}

internal class SysPowerConfig : EntityTypeConfiguration<SysPower>
{
    SysPowerConfig()
    {
        ToTable("Sys_Power");
    }
}

}
