//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fr.Model
{
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Entity.ModelConfiguration;
    using System;
    using System.Collections.Generic;
    
    [Table("Sys_Power")]
    public partial class SysPower
    {
    	/// <summary>
    	/// 功能Id
    	/// </summary>
    	[StringLength(50)]
    		
    	public string PowerId { get; set; }
    	/// <summary>
    	/// 功能编码
    	/// </summary>
    	[StringLength(200)]
    		
    	public string PowerCode { get; set; }
    	/// <summary>
    	/// 功能名称
    	/// </summary>
    	[StringLength(200)]
    		
    	public string PowerName { get; set; }
    }
    
    internal class SysPowerConfig : EntityTypeConfiguration<SysPower>
    {
        SysPowerConfig()
        {
            ToTable("Sys_Power");
        }
    }
}
