//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Agent
    {
        public string AgentId { get; set; }
        public string UserId { get; set; }
        public string ParentId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUserId { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string ModifyUserId { get; set; }
        public string CreateUserName { get; set; }
        public string ModifyUserName { get; set; }
    }
}
