//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_LogDetail
    {
        public string SysLogDetailId { get; set; }
        public string SysLogId { get; set; }
        public string PropertyName { get; set; }
        public string PropertyField { get; set; }
        public string NewValue { get; set; }
        public string OldValue { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
