//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Button
    {
        public string ButtonId { get; set; }
        public string MenuId { get; set; }
        public string ParentId { get; set; }
        public string Code { get; set; }
        public string ButtonName { get; set; }
        public string Category { get; set; }
        public string JsEvent { get; set; }
        public string ActionEvent { get; set; }
        public string Remark { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<int> SortCode { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string ModifyUserId { get; set; }
        public string ModifyUserName { get; set; }
    }
}
