
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fr
{

using System;
    using System.Collections.Generic;
    
public partial class Sys_Employee
{

    public string EmployeeId { get; set; }

    public string CompanyId { get; set; }

    public string DepartmentId { get; set; }

    public string EmployeeName { get; set; }

    public string IdCard { get; set; }

    public Nullable<System.DateTime> Birthday { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public Nullable<int> Status { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public string CreateUserId { get; set; }

    public string CreateUserName { get; set; }

    public Nullable<System.DateTime> ModifyTime { get; set; }

    public string ModifyUserId { get; set; }

    public string ModifyUserNaame { get; set; }

}

}
