
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fr
{

using System;
    using System.Collections.Generic;
    
public partial class Sys_Company
{

    public string CompanyId { get; set; }

    public string CompanyName { get; set; }

    public byte Status { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public string CreateUserId { get; set; }

    public Nullable<System.DateTime> ModifyTime { get; set; }

    public string ModifyUserId { get; set; }

    public string CreateUserName { get; set; }

    public string ModifyUserName { get; set; }

    public string ParentId { get; set; }

    public string Nature { get; set; }

    public string Manager { get; set; }

    public string Contact { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Fax { get; set; }

    public string WebSite { get; set; }

    public string AccountInfo { get; set; }

    public string Adress { get; set; }

    public string Remark { get; set; }

    public Nullable<int> SortOrder { get; set; }

}

}
