
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fr.Service
{ 

using Fr.IService;
using Fr.IRepositories;
using Fr.Repositories;
using System;
    using System.Collections.Generic;
    
public partial class SysUserRolePowerService:ISysUserRolePowerService
{ 
	ISysUserRolePowerRepository _repository ;

	/// <summary>
	/// 构造函数注入
	/// </summary>
	/// <param name="repository"></param>
	public SysUserRolePowerService(ISysUserRolePowerRepository repository){
		_repository = repository;
	} 
}

	
}
