//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fr.Service
{ 
    using Fr.IService;
    using Fr.IRepositories;
    using Fr.Repositories;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Fr.Model;
    
    public partial class SysCompanyService:ISysCompanyService
    { 
    	ISysCompanyRepository _repository ;
    
    	/// <summary>
    	/// 构造函数注入
    	/// </summary>
    	/// <param name="repository"></param>
    	public SysCompanyService(ISysCompanyRepository repository){
    		_repository = repository;
    	}


        public List<SysCompany> GetCompanyList()
        {
            var source = _repository.Source.Where(c => c.Status != StateEnum.启用).OrderBy(c => c.CompanyName).ToList();
            return source;
        } 
    }
	
}
