//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fr.Service
{ 
    using Fr.IService;
    using Fr.IRepositories;
    using Fr.Repositories;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Fr.Model;
    using Fr.Utilily;
    
    public partial class SysCompanyService:ISysCompanyService
    { 
    	ISysCompanyRepository _repository ;
    
    	/// <summary>
    	/// 构造函数注入
    	/// </summary>
    	/// <param name="repository"></param>
    	public SysCompanyService(ISysCompanyRepository repository){
    		_repository = repository;
    	}


        public List<SysCompany> GetCompanyList()
        {
            var source = _repository.Source.Where(c => c.Status != StateEnum.启用).OrderBy(c => c.CompanyName).ToList();
            return source;
        }


        public SysCompany GetCompanyInfo(string keyId)
        {
            var entity = _repository.Find(c => c.CompanyId == keyId && c.Status == StateEnum.启用).FirstOrDefault();
            return entity;
        }

        public bool SaveCompanyInfo(string keyId,SysCompany data)
        {
            if(data ==null || string.IsNullOrEmpty(data.CompanyId ))
                throw new ArgumentNullException("参数错误");
            var user = SysUserHelper.CurrentUser;
            if (string.IsNullOrEmpty(keyId))
            {
                data.CreateTime = DateTime.Now;
                data.CreateUserId = user.UserId;
                data.CreateUserName = user.NickName;
                data.ModifyTime = DateTime.Now;
                data.ModifyUserId = user.UserId;
                _repository.Insert(data);
            }
            else
            {
                data.CompanyId = keyId;
                data.ModifyUserId = user.UserId;
                data.ModifyUserName = user.NickName;
                data.ModifyTime = DateTime.Now;
                _repository.Save(data);
            }
            return true;
        }

                
    }
	
}
