//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fr.Service
{ 
    using Fr.IService;
    using Fr.IRepositories;
    using Fr.Repositories;
    using System;
    using System.Linq;
    using System.Collections.Generic;
    
    public partial class SysRoleService:ISysRoleService
    { 
    	ISysRoleRepository _repository ;
    
    	/// <summary>
    	/// 构造函数注入
    	/// </summary>
    	/// <param name="repository"></param>
    	public SysRoleService(ISysRoleRepository repository){
    		_repository = repository;
    	}



        public Model.SysRole GetSysRole(string userId)
        {
           return  _repository.Source.Where(c => c.RoleId==userId).FirstOrDefault();
        }
    }
	
}
