//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fr.Service
{ 
    using Fr.IService;
    using Fr.IRepositories;
    using Fr.Repositories;
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Fr.Utilily;
    
    public partial class SysShortcutsService:ISysShortcutsService
    { 
    	ISysShortcutsRepository _repository ;
    
    	/// <summary>
    	/// 构造函数注入
    	/// </summary>
    	/// <param name="repository"></param>
    	public SysShortcutsService(ISysShortcutsRepository repository){
    		_repository = repository;
    	}

        public List<Model.SysMenu> GetShortcutList(string userId)
        { 
            return _repository.Source.Where(c => c.CreateUserId == userId).Select(c=>c.SysMenu).ToList();
        }


      

        public void SaveShortcuts(string menuId, string userId)
        {
            var entity = _repository.Source.Where(c => c.MenuId == menuId && c.UserId == userId ).FirstOrDefault();
            if (entity != null) return;
            var currentUser =SysUserHelper.CurrentUser;
            entity = new Model.SysShortcuts()
            {
                CreateTime= DateTime.Now,
                UserId= currentUser.UserId,
                CreateUserId=userId,
                CreateUserName = currentUser.NickName,
                ModifyTime = DateTime.Now,
                ModifyUserId = currentUser.UserId,
                ModifyUserName = currentUser.NickName,
                ShortcutsId = Guid.NewGuid().ToString("N"),
                MenuId = menuId
            };
            _repository.Insert(entity);
        }
    }
	
}
