
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fr.Model
{

using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity.ModelConfiguration;
using System;
    using System.Collections.Generic;
    
[Table("Sys_Company")]
public partial class SysCompany
{

	/// <summary>
	/// 公司Id
	/// </summary>
	
	[StringLength(50),Key]
	
	public string CompanyId { get; set; }

    /// <summary>
    /// 公司编码
    /// </summary>
    [StringLength(50)]
    public string Code { get; set; }

	/// <summary>
	/// 公司名称
	/// </summary>
	
	[StringLength(200)]
	
	public string CompanyName { get; set; }

	/// <summary>
	/// 状态
	/// </summary>

    public RecordStateEnum Status { get; set; }

	/// <summary>
	/// 创建时间
	/// </summary>
	
	public System.DateTime? CreateTime { get; set; }

	/// <summary>
	/// 创建人
	/// </summary>
	
	[StringLength(50)]
	
	public string CreateUserId { get; set; }

	/// <summary>
	/// 修改时间
	/// </summary>
	
	public System.DateTime? ModifyTime { get; set; }

	/// <summary>
	/// 修改人
	/// </summary>
	
	[StringLength(50)]
	
	public string ModifyUserId { get; set; }

	/// <summary>
	/// 创建人
	/// </summary>
	
	[StringLength(200)]
	
	public string CreateUserName { get; set; }

	/// <summary>
	/// 修改人
	/// </summary>
	
	[StringLength(200)]
	
	public string ModifyUserName { get; set; }

	/// <summary>
	/// 上级公司Id
	/// </summary>
	
	[StringLength(50)]
	
	public string ParentId { get; set; }

	/// <summary>
	/// 公司性质 
	/// </summary>
	
	[StringLength(50)]
	
	public string Nature { get; set; }

	/// <summary>
	/// 法人
	/// </summary>
	
	[StringLength(50)]
	
	public string Manager { get; set; }

	/// <summary>
	/// 联系人
	/// </summary>
	
	[StringLength(50)]
	
	public string Contact { get; set; }

	/// <summary>
	/// 手机
	/// </summary>
	
	[StringLength(50)]
	
	public string Phone { get; set; }

	/// <summary>
	/// 电子邮箱
	/// </summary>
	
	[StringLength(200)]
	
	public string Email { get; set; }

	/// <summary>
	/// 传真
	/// </summary>
	
	[StringLength(50)]
	
	public string Fax { get; set; }

	/// <summary>
	///网站
    /// </summary>
	
	[StringLength(200)]
	
	public string WebSite { get; set; }

	/// <summary>
	/// 开户信息
	/// </summary>
	
	[StringLength(200)]
	
	public string AccountInfo { get; set; }

	/// <summary>
	/// 公司地址
	/// </summary>
	
	[StringLength(200)]
	
	public string Adress { get; set; }

	/// <summary>
	/// 公司简介
	/// </summary>
	
	[StringLength(2000)]
	
	public string Remark { get; set; }

	/// <summary>
	/// 排序
	/// </summary>
	
	public int? SortOrder { get; set; }

}

internal class SysCompanyConfig : EntityTypeConfiguration<SysCompany>
{
    SysCompanyConfig()
    {
        ToTable("Sys_Company");
    }
}

}
