
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fr.Model
{

using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity.ModelConfiguration;
using System;
    using System.Collections.Generic;
    
[Table("Sys_MenuPermission")]
public partial class SysMenuPermission
{

	/// <summary>
	/// 
	/// </summary>
	
    [StringLength(50),Key]
	
	
	public string MenuPermissionId { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
    [StringLength(50)]
	
	
	public string MenuId { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	
	public int? SortCode { get; set; }

	/// <summary>
	/// 
	/// </summary>


    public RecordStateEnum Status { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
    [StringLength(200)]
	
	
	public string Remark { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
	
	public System.DateTime? CreateTime { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
    [StringLength(50)]
	
	
	public string CreateUserId { get; set; }

	/// <summary>
	/// 
	/// </summary>
	
    [StringLength(200)]
	
	
	public string CreateUserName { get; set; }

	/// <summary>
	/// 
	/// </summary>
	public System.DateTime? ModifyTime { get; set; }

	/// <summary>
	/// 修改人Id
	/// </summary>
	
    [StringLength(50)]
	public string ModifyUserId { get; set; }

	/// <summary>
	/// 修改人
	/// </summary>
	
    [StringLength(200)]
	
	
	public string ModifyUserName { get; set; }

	/// <summary>
	/// 角色Id
	/// </summary>
	
    [StringLength(50)]
	
	
	public string RoleId { get; set; }
    
    public SysMenu SysMenu { get; set; }

}

internal class SysMenuPermissionConfig : EntityTypeConfiguration<SysMenuPermission>
{
    SysMenuPermissionConfig()
    {
        ToTable("Sys_MenuPermission");
        HasOptional(x => x.SysMenu).WithMany().HasForeignKey(c => c.MenuId);
    }
}

}
