//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fr.Adapter
{
    using Fr.Dto.System;
    using Fr.IAdapter;
    using Fr.IService;
    using Fr.Model;
    using Fr.Service;
    using System;
    using System.Collections.Generic;

    public partial class SysCompanyAdapter : ISysCompanyAdapter
    {
        ISysCompanyService _service;

        public SysCompanyAdapter(ISysCompanyService service)
        {
            _service = service;
        }
        public List<SysCompanyDto> GetCompanyList()
        {
            return _service.GetCompanyList().ToListModel<SysCompanyDto, SysCompany>();
        }


        public SysCompanyDto GetCompanyInfo(string keyId)
        {
            return _service.GetCompanyInfo(keyId).ToModel<SysCompanyDto>();
        }

        public bool SaveCompanyInfo(string keyId,SysCompanyDto data)
        {
            return _service.SaveCompanyInfo(keyId,data.ToModel<SysCompany>()); 
        }


        public void Delete(string keyId)
        {
             _service.Delete(keyId);
        }
    }
	
}
