//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fr.Adapter
{
    using Fr.Dto.System;
    using Fr.IAdapter;
    using Fr.IService;
    using Fr.Model;
    using System;
    using System.Collections.Generic;
    
    public  class SysMenuPermissionAdapter:ISysMenuPermissionAdapter
    {
        ISysMenuPermissionService _service;
        public SysMenuPermissionAdapter(ISysMenuPermissionService service)
        {
            _service = service;
        }
        public List<Dto.System.SysMenuDto> GetModuleList(string roleId)
        {
            return _service.GetModuleList(roleId).ToListModel<SysMenuDto, SysMenu>();
        }
    }
}
