//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fr.Adapter
{
    using Fr.Dto.System;
    using Fr.IAdapter;
    using Fr.IService;
    using Fr.Model;
    using System;
    using System.Collections.Generic; 
    public  class SysShortcutsAdapter:ISysShortcutsAdapter
    {
        ISysShortcutsService _service;

        public SysShortcutsAdapter(ISysShortcutsService service)
        {
            _service = service;
        }
        public List<SysMenuDto> GetShortcutList(string userId)
        {
            return _service.GetShortcutList(userId).ToListModel<SysMenuDto,SysMenu>();
        }


        public void SaveShortcuts(string menuId, string userId)
        {
            _service.SaveShortcuts(menuId, userId);
        }
    }
}
