//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fr.Adapter
{ 
    using Fr.IService;
    using Fr.Service;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Fr.Model;
    using Fr.Dto.System;
    using Fr.IAdapter;

    public partial class SysUserAdapter : ISysUserAdapter
    {
        ISysUserService _service;
        public SysUserAdapter(ISysUserService service)
        {
            _service = service;
        }
        
        public bool Add(SysUserDto user)
        {
            return _service.Add(user.ToModel<SysUser>());
        }
    

        public SysUserDto Get(string userId)
        {
            return _service.Get(userId).ToModel<SysUserDto>(); 
        }

        public List<SysUserDto> GetUserList(int index, int size, out int total)
        {
            return _service.GetUserList(index, size, out total).ToListModel<SysUserDto, SysUser>();
        }

        public SysUserDto Login(string loginName,string password)
        {
            return _service.Login(loginName, password).ToModel<SysUserDto>(); 
        }
    }
	
}
