//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fr.IAdapter
{
    using Fr.Dto.System;
    using System;
    using System.Collections.Generic;

    public interface ISysRoleAdapter
    {
        /// <summary>
        /// 获取用户角色
        /// </summary>
        /// <param name="userId"></param>
        /// <returns></returns>

        SysRoleDto GetSysRole(string userId);
    }
}
