//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fr.IAdapter
{
    using Fr.Dto.System;
    using System;
    using System.Collections.Generic;
    
    public  interface ISysShortcutsAdapter
    {
        /// <summary>
        /// 获取快捷方式
        /// </summary>
        /// <param name="userId"></param>
        /// <returns></returns>
        List<SysMenuDto> GetShortcutList(string userId);

        void SaveShortcuts(string menuId, string userId);
    }
}
