//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fr.IAdapter
{
    using Fr.Dto.System;
    using System;
    using System.Collections.Generic;

    public interface ISysUserAdapter
    {
        bool Add(SysUserDto user);

        SysUserDto Get(string userId);

        List<SysUserDto> GetUserList(int index, int size, out int total);

        SysUserDto Login(string loginName, string password);
    }
}
